@echo off
del MWMusicEditor.prg
del Demo.prg

IF "%1%" == "n" GOTO skiptests

call RunTests.bat
echo Error level = %ERRORLEVEL%
IF ERRORLEVEL 1 goto :error

:skiptests

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

..\acme.exe -v4 --msvc Editor.a
if not exist MWMusicEditor.prg goto error
..\bin\LZMPi.exe -c64b MWMusicEditor.prg MWMusicEditor.prg $c00 >t.txt
if not exist MWMusicEditor.prg goto error



Release\CompactorTool.exe -i bin\snarev2.mus -o t.a
..\acme.exe -v4 --msvc Demo.a
if not exist Demo.prg goto error
..\bin\LZMPi.exe -c64b Demo.prg Demo.prg $c00 >t.txt
if not exist Demo.prg goto error



goto end
:error
echo MWMusicEditor.prg not created!
exit /B -1
:end
