@echo off

rem No extra Ultimax boot, so use a simple empty address switch as placeholder for the command line
set CART_BOOT_TYPE=-tg
set CART_BOOT_TYPE_HI=-a $8000
rem Using Ultimax boot, so create the high bank with the reset vector
rem set CART_BOOT_TYPE=-te
rem set CART_BOOT_TYPE_HI=-a $a000 -b 0 -c $1ffc 2 4 -w

echo CART_BOOT_TYPE = %CART_BOOT_TYPE%

del Data\*.lng
..\acme.exe --setpc $8000 --cpu 6502 -f plain -o Data\TextFrench.lng TextTableMacros.a TextTable.a TextFrench.a
..\acme.exe --setpc $8000 --cpu 6502 -f plain -o Data\TextItalian.lng TextTableMacros.a TextTable.a TextItalian.a
..\acme.exe --setpc $8000 --cpu 6502 -f plain -o Data\TextGerman.lng TextTableMacros.a TextTable.a TextGerman.a
..\acme.exe --setpc $8000 --cpu 6502 -f plain -o Data\TextSpanish.lng TextTableMacros.a TextTable.a TextSpanish.a

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

IF EXIST AnimationBitmap.prg del /Q AnimationBitmap.prg
..\acme.exe -v4 --msvc AnimationBitmapPre.a AnimationBitmap.a
if not exist AnimationBitmap.prg goto error
..\bin\LZMPi.exe -c64m AnimationBitmap.prg AnimationBitmap.prg $c000 >t.txt
if not exist AnimationBitmap.prg goto error

..\bin\MakeCart.exe %CART_BOOT_TYPE% -n -a $8000 -b 0 -r ..\Citadel2\Citadel2Cart_8K.prg -c 0 2 $ffff -w %CART_BOOT_TYPE_HI% -r AnimationBitmap.prg -a $8000 -b 1 -c 0 $0001 $ffff -w -a $8000 -b 2 -c 0 $2001 $ffff -w -a $8000 -b 3 -c 0 $4001 $ffff -w -a $8000 -b 4 -c 0 $6001 $ffff -w -a $8000 -b 5 -c 0 $8001 $ffff -w -a $8000 -b 6 -c 0 $a001 $ffff -w -a $8000 -b 22 -m data\frm0*.del $2000 -o AnimationBitmapPreview.crt



IF EXIST AnimationBitmap.prg del /Q AnimationBitmap.prg
..\acme.exe -v4 --msvc AnimationBitmap.a
if not exist AnimationBitmap.prg goto error
..\bin\LZMPi.exe -c AnimationBitmap.prg AnimationBitmap.cmp 2 >t.txt
IF EXIST AnimationBitmap.prg del /Q AnimationBitmap.prg
pushd ..\Decompression
IF EXIST TestDecompression.prg del /Q TestDecompression.prg
..\acme.exe -v4 --msvc EnableFireCheck.a TestDecompression3CyberLoad.a AnimationBitmapDefines.a LauncherAddressCalc.a
copy /y TestDecompression.prg ..\AnimationBitmap\AnimationBitmap.prg
popd
if not exist AnimationBitmap.prg goto error

..\bin\MakeCart.exe %CART_BOOT_TYPE% -n -a $8000 -b 0 -r ..\Citadel2\Citadel2Cart_8K.prg -c 0 2 $ffff -w %CART_BOOT_TYPE_HI% -r AnimationBitmap.prg -a $8000 -b 1 -c 0 $0001 $ffff -w -a $8000 -b 2 -c 0 $2001 $ffff -w -a $8000 -b 3 -c 0 $4001 $ffff -w -a $8000 -b 4 -c 0 $6001 $ffff -w -a $8000 -b 5 -c 0 $8001 $ffff -w -a $8000 -b 6 -c 0 $a001 $ffff -w -a $8000 -b 22 -m data\frm0*.del $2000 -o AnimationBitmap.crt

C:\Downloads\WinVICE-3.1-x86-r34062\WinVICE-3.1-x86-r34062\cartconv.exe -i AnimationBitmap.crt -t bin -o AnimationBitmap.bin

goto end
:error
echo AnimationBitmap.prg not created!
exit /B -1
:end
