@echo off
del Footy.prg FootyCmp.prg
del Footy.crt
if not exist bin mkdir bin
del bin\*.bin

rem Using Ultimax boot, so create the high bank with the reset vector
set CART_BOOT_TYPE=-te
set CART_BOOT_TYPE_HI=-a $a000 -b 0 -c $1ffc 2 4 -w

echo CART_BOOT_TYPE = %CART_BOOT_TYPE%


echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

..\acme.exe --lib asm/ --lib ../ --lib ../SpriteMultiplexor/ --lib ../stdlib/ -v4 --msvc Footy.a
if not exist Footy.prg goto error
rem ..\bin\LZMPi.exe -c64 Footy.prg Footy.prg $400 >t.txt
..\bin\LZMPi.exe -c64mr Footy.prg FootyCmp.prg $400 >t.txt
if not exist FootyCmp.prg goto error

echo ;This file is automatically generated by BuildIt.bat >bin\CartOpts.a

rem Extract all the required variables from this list to a separate file
for %%x in (
	PitchMapData
) do (
	..\ExternalTools\Gnu\bin\sed.exe -n "/%%x/p" Footy.map >>bin\CartOpts.a
)

for /L %%x in (0,1,26) do (
	echo MapYPos = %%x >bin\MapYPos.a
	..\acme.exe --msvc --lib ../ --lib asm/ -o bin\Scroll%%x.bin bin\CartOpts.a bin\MapYPos.a PitchDrawUnrolled.a
)

set FOOTY_SPEED_CODE_FILES_NUM=27
set FOOTY_SPEED_CODE_FILES=bin\Scroll0.bin bin\Scroll1.bin bin\Scroll2.bin bin\Scroll3.bin bin\Scroll4.bin bin\Scroll5.bin bin\Scroll6.bin bin\Scroll7.bin bin\Scroll8.bin bin\Scroll9.bin bin\Scroll10.bin bin\Scroll11.bin bin\Scroll12.bin bin\Scroll13.bin bin\Scroll14.bin bin\Scroll15.bin bin\Scroll16.bin bin\Scroll17.bin bin\Scroll18.bin bin\Scroll19.bin bin\Scroll20.bin bin\Scroll21.bin bin\Scroll22.bin bin\Scroll23.bin bin\Scroll24.bin bin\Scroll25.bin bin\Scroll26.bin


..\bin\MakeCart.exe -i _f_index1.a %CART_BOOT_TYPE% -n -a $8000 -b 0 -r ..\Citadel2\Citadel2Cart_8K.prg -c 0 2 $ffff -w %CART_BOOT_TYPE_HI% -r FootyCmp.prg -a $8000 -b 1 -c 0 $0001 $ffff -w -a $8000 -b 2 -c 0 $2001 $ffff -w -a $8000 -b 3 -c 0 $4001 $ffff -w -a $8000 -b 4 -c 0 $6001 $ffff -w -a $8000 -b 5 -c 0 $8001 $ffff -w -a $8000 -b 6 -c 0 $a001 $ffff -w -a $8000 -b 7 -f $2000 %FOOTY_SPEED_CODE_FILES_NUM% %FOOTY_SPEED_CODE_FILES% -o Footy.crt >tf.txt
if not exist Footy.crt goto error

rem Build the final code again to get the offsets
..\acme.exe --lib asm/ --lib ../ --lib ../SpriteMultiplexor/ --lib ../stdlib/ -v4 --msvc Footy.a >>tf.txt
if not exist Footy.prg goto error
rem ..\bin\LZMPi.exe -c64 Footy.prg Footy.prg $400 >t.txt
..\bin\LZMPi.exe -c64mr Footy.prg FootyCmp.prg $400 >t.txt
if not exist FootyCmp.prg goto error

..\bin\MakeCart.exe -i _f_index1.a %CART_BOOT_TYPE% -n -a $8000 -b 0 -r ..\Citadel2\Citadel2Cart_8K.prg -c 0 2 $ffff -w %CART_BOOT_TYPE_HI% -r FootyCmp.prg -a $8000 -b 1 -c 0 $0001 $ffff -w -a $8000 -b 2 -c 0 $2001 $ffff -w -a $8000 -b 3 -c 0 $4001 $ffff -w -a $8000 -b 4 -c 0 $6001 $ffff -w -a $8000 -b 5 -c 0 $8001 $ffff -w -a $8000 -b 6 -c 0 $a001 $ffff -w -a $8000 -b 7 -f $2000 %FOOTY_SPEED_CODE_FILES_NUM% %FOOTY_SPEED_CODE_FILES% -o Footy.crt >>tf.txt
if not exist Footy.crt goto error

goto end
:error
type tf.txt
echo FootyCmp.prg not created!
exit /B -1
:end
