@echo off
del FLDParalax.prg

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

..\..\acme.exe -v4 --msvc --lib ../ --lib ../../ --lib ../../stdlib/ FLDParalax.a
if not exist FLDParalax.prg goto error
..\..\bin\LZMPi.exe -t $ff00 -c64mrb FLDParalax.prg FLDParalax.prg $400 >t.txt
rem ..\..\bin\LZMPi.exe -c64mbu FLDParalax.prg FLDParalax.prg $400 >t.txt
if not exist FLDParalax.prg goto error
goto end
:error
echo FLDParalax.prg not created!
exit /B -1
:end
