rem @echo off
rem Citadel2Cart_8K.prg
del Citadel2.prg DataLevel1.prg Citadel2.crt Citadel2Cart_8K.prg Citadel2_Title.prg Citadel2_Game.prg
del Citadel2_Title.cmp Citadel2_Game.cmp
del Citadel2.crt Citadel2.bin

rem No extra Ultimax boot, so use a simple empty address switch as placeholder for the command line
set CART_BOOT_TYPE=-tg
set CART_BOOT_TYPE_HI=-a $8000
rem Using Ultimax boot, so create the high bank with the reset vector
set CART_BOOT_TYPE=-te
set CART_BOOT_TYPE_HI=-a $a000 -b 0 -c $1ffc 2 4 -w

echo CART_BOOT_TYPE = %CART_BOOT_TYPE%

echo ******** Assembling Citadel2Cart.a
..\acme.exe -v3 --msvc Citadel2Cart.a
if not exist Citadel2Cart_8K.prg goto error

echo ******** Assembling DataScorePanel.a
..\acme.exe -v3 --msvc --lib ../Scroller/ asm\DataScorePanel.a
if not exist DataScorePanel.prg goto error

echo ******** Assembling DataLevel1.a
..\acme.exe -v3 --msvc asm\DataLevel1.a
if not exist DataLevel1.prg goto error
..\ExternalTools\Gnu\bin\sed.exe -n -e "s/MapData. =\$//p" DataLevel1.map | ..\ExternalTools\Gnu\bin\sed.exe -n -e "s/;.*//p" > _tmpFile
set /p CODE_MAPDATA= < _tmpFile
..\ExternalTools\Gnu\bin\sed.exe -n -e "s/SolidMapBlockIndex. =\$//p" DataLevel1.map | ..\ExternalTools\Gnu\bin\sed.exe -n -e "s/;.*//p" > _tmpFile
set /p CODE_SOLIDMAPBLOCKINDEX= < _tmpFile

Release\MapCreateZones.exe DataLevel1.prg $%CODE_MAPDATA% $%CODE_SOLIDMAPBLOCKINDEX% ZonesLevel1.bin

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >FingerPrint.a

echo ;This file is automatically generated by BuildIt.bat >DataAutoDefs.a

rem Extract all the required variables from this list to a separate file
for %%x in (
	AnimationTypeTableHi
	AnimationTypeTableLo
	BlockColours
	BlockData
	CharColours
	EnemyType
	EnemyFlags_SpawnList
	EnemyTemplate_SpawnList
	EnemyPositionsX
	EnemyPositionsY
	EnemyFlags
	InterestingPlacesX
	InterestingPlacesY
	InterestingPlacesZone
	MapAnimationTypeTableLo
	MapAnimationTypeTableHi
	MapData
	MapTerminalToDoor
	MapAutoDoor
	NumInterestingPlaces
	TeleportPairs
	EnemyTemplate_Animation
	EnemyTemplate_Speed
	EnemyTemplate_Health
	EnemyTemplate_Alertness
	EnemyTemplate_Ram
	EnemyTemplate_CaptureEnergyCost
	EnemyTemplate_SpawnList
) do (
	..\ExternalTools\Gnu\bin\sed.exe -n "/%%x/p" DataLevel1.map >>DataAutoDefs.a
)

for %%x in (
	ScorePanelChars
	ScorePanelCharData
	TitleScreenChars
	TitleScreenCharData
	TitleScreenBallSprites
) do (
	..\ExternalTools\Gnu\bin\sed.exe -n "/%%x/p" DataScorePanel.map >>DataAutoDefs.a
)


rem ********************************************************************
echo ******** Assembling Citadel2Entry_Title.a
..\acme.exe -f cbm -v3 --msvc --lib ../Scroller/ --lib ../Decompression/ Citadel2Entry.a Citadel2Entry_Title.a Citadel2Entry_Title_Stubs.a DataAutoDefs.a
ren Citadel2.prg Citadel2_Title.prg
if not exist Citadel2_Title.prg goto error

..\ExternalTools\Gnu\bin\sed.exe -n -e "s/GenericSpecificCode_End. =\$//p" Citadel2.map | ..\ExternalTools\Gnu\bin\sed.exe -n -e "s/;.*//p" > _tmpFile
set /p CODE_TITLE_START= < _tmpFile
set /A FILE_TITLE_START=0x%CODE_TITLE_START% + 2 - 0x200

..\ExternalTools\Gnu\bin\sed.exe -n -e "s/TitleScreenSpecificCode_End. =\$//p" Citadel2.map | ..\ExternalTools\Gnu\bin\sed.exe -n -e "s/;.*//p" > _tmpFile
set /p CODE_TITLE_END= < _tmpFile
set /A FILE_TITLE_END=0x%CODE_TITLE_END% + 2 - 0x200

set /A FILE_TITLE_SIZE=%FILE_TITLE_END% - %FILE_TITLE_START%

..\bin\LZMPi.exe -c Citadel2_Title.prg Citadel2_Title.cmp %FILE_TITLE_START% %FILE_TITLE_SIZE%
..\bin\LZMPi.exe -d Citadel2_Title.cmp Citadel2_Title.dec


rem ********************************************************************
echo ******** Assembling Citadel2Entry_Game.a
..\acme.exe -f cbm -v3 --msvc --lib ../Scroller/ --lib ../Decompression/ Citadel2Entry.a Citadel2Entry_Game.a asm/Data.a ../Scroller/DataCheck.a
ren Citadel2.prg Citadel2_Game.prg
if not exist Citadel2_Game.prg goto error

..\ExternalTools\Gnu\bin\sed.exe -n -e "s/GenericSpecificCode_End. =\$//p" Citadel2.map | ..\ExternalTools\Gnu\bin\sed.exe -n -e "s/;.*//p" > _tmpFile
set /p CODE_GAME_START= < _tmpFile
set /A FILE_GAME_START=0x%CODE_GAME_START% + 2 - 0x200
set /A FILE_GAME2_START=0x%CODE_GAME_START% + 2 - 0x200 + 0x2000
set /A FILE_GAME3_START=0x%CODE_GAME_START% + 2 - 0x200 + 0x2000 + 0x2000

..\ExternalTools\Gnu\bin\sed.exe -n -e "s/GameSpecificCode_End. =\$//p" Citadel2.map | ..\ExternalTools\Gnu\bin\sed.exe -n -e "s/;.*//p" > _tmpFile
set /p CODE_GAME_END= < _tmpFile
set /A FILE_GAME2_END=0x%CODE_GAME_END% + 2 - 0x200
set /A FILE_GAME3_END=0x%CODE_GAME_END% + 2 - 0x200

set /A FILE_GAME_SIZE=0x2000
set /A FILE_GAME2_SIZE=%FILE_GAME2_END% - %FILE_GAME2_START%
set /A FILE_GAME3_SIZE=%FILE_GAME3_END% - %FILE_GAME3_START%

..\bin\LZMPi.exe -c Citadel2_Game.prg Citadel2_Game.cmp %FILE_GAME_START% %FILE_GAME_SIZE%
..\bin\LZMPi.exe -c Citadel2_Game.prg Citadel2_Game2.cmp %FILE_GAME2_START% %FILE_GAME2_SIZE%
..\bin\LZMPi.exe -c Citadel2_Game.prg Citadel2_Game3.cmp %FILE_GAME3_START% %FILE_GAME3_SIZE%
..\bin\LZMPi.exe -d Citadel2_Game.cmp Citadel2_Game.dec
..\bin\LZMPi.exe -d Citadel2_Game2.cmp Citadel2_Game2.dec
..\bin\LZMPi.exe -d Citadel2_Game3.cmp Citadel2_Game3.dec


del _tmpFile


..\bin\LZMPi.exe -c64m Citadel2_Game.prg Citadel2.prg $200 >>t.txt
if not exist Citadel2.prg goto error


rem ** Assume speed code always enabled for this game
..\ExternalTools\Gnu\bin\sed.exe -n "/Scroller_EnableSpeedCode/q1" Citadel2.map
IF NOT ERRORLEVEL 1 goto errorSpeed

echo ;This file is automatically generated by BuildIt.bat >..\Scroller\CartCode\CartOpts.a

rem Extract all the required variables from this list to a separate file
for %%x in (
	Scroller_EnableSpeedCode
	Scroller_EnableBlockColourSpeedCode
	Scroller_NeedFullColourScroll
	Scroller_Debug
	CharColoursForEveryCharacter
	ScrollerLongBranch
	Scroller_KillCartridgeBank
	Scroller_BankSwitchControl
	Scroller_ScrollBankEntry
	ScrollBankSplit
	Scroller_FullScreen
	ColourTemp
	CharColours
	topScreenBank
	BankToScreenAddr
	COLOURRAM
) do (
	..\ExternalTools\Gnu\bin\sed.exe -n "/%%x/p" Citadel2.map >>..\Scroller\CartCode\CartOpts.a
)

if not exist bin mkdir bin
del bin\*.bin

rem Create the cartridge Citadel2 speed code
echo ScreenA = $c800 >..\Scroller\CartCode\ScreenConfig.a
echo ScreenB = $cc00 >>..\Scroller\CartCode\ScreenConfig.a

..\ExternalTools\Gnu\bin\sed.exe -n "/Scroller_EnableBlockColourSpeedCodeInCart/q1" Citadel2.map
IF NOT ERRORLEVEL 1 goto noColourise
echo Adding speed colourise code
..\acme.exe --msvc -o bin\ColouriseTop.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\HeaderEntry.a ..\Scroller\ScrollerStripsMacros.a ..\Scroller\ScrollerStripsColouriseTop.a
..\acme.exe --msvc -o bin\ColouriseBottom.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\HeaderEntry.a ..\Scroller\ScrollerStripsMacros.a ..\Scroller\ScrollerStripsColouriseBottom.a
..\acme.exe --msvc -o bin\ColouriseLeft.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\HeaderEntry.a ..\Scroller\ScrollerStripsMacros.a ..\Scroller\ScrollerStripsColouriseLeft.a
..\acme.exe --msvc -o bin\ColouriseRight.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\HeaderEntry.a ..\Scroller\ScrollerStripsMacros.a ..\Scroller\ScrollerStripsColouriseRight.a
:noColourise

..\acme.exe --msvc -o bin\Char0To1_1.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_1.a
..\acme.exe --msvc -o bin\Char0To1_m1.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_m1.a
..\acme.exe --msvc -o bin\Char0To1_40.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_40.a
..\acme.exe --msvc -o bin\Char0To1_m40.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_m40.a

echo ScreenA = $cc00 >..\Scroller\CartCode\ScreenConfig.a
echo ScreenB = $c800 >>..\Scroller\CartCode\ScreenConfig.a
..\acme.exe --msvc -o bin\Char1To0_1.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_1.a
..\acme.exe --msvc -o bin\Char1To0_m1.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_m1.a
..\acme.exe --msvc -o bin\Char1To0_40.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_40.a
..\acme.exe --msvc -o bin\Char1To0_m40.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_m40.a

echo ScreenA = $d800 >..\Scroller\CartCode\ScreenConfig.a
echo ScreenB = $d800 >>..\Scroller\CartCode\ScreenConfig.a
echo ScreenBTemp = ColourTemp >>..\Scroller\CartCode\ScreenConfig.a
..\acme.exe --msvc -o bin\Colour_1.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_1.a
..\acme.exe --msvc -o bin\Colour_m1.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_m1.a
..\acme.exe --msvc -o bin\Colour_40.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_40.a
..\acme.exe --msvc -o bin\Colour_m40.bin --lib ..\Scroller\CartCode\ ..\Scroller\CartCode\Header.a ..\Scroller\CartCode\Scroll_m40.a

rem If the files are missing then they are simply not included in the cart
set SCROLLER_SPEED_CODE_FILES_NUM=28
set SCROLLER_SPEED_CODE_FILES=bin\ColouriseTop.bin+! bin\Char0To1_1.bin bin\Char1To0_1.bin bin\ColouriseBottom.bin+! bin\Char0To1_m1.bin bin\Char1To0_m1.bin bin\ColouriseLeft.bin+! bin\Char0To1_40.bin bin\Char1To0_40.bin bin\ColouriseRight.bin+! bin\Char0To1_m40.bin bin\Char1To0_m40.bin bin\Char0To1_41.bin bin\Char1To0_41.bin bin\Char0To1_39.bin bin\Char1To0_39.bin bin\Char0To1_m41.bin bin\Char1To0_m41.bin bin\Char0To1_m39.bin bin\Char1To0_m39.bin bin\Colour_1.bin bin\Colour_m1.bin bin\Colour_40.bin bin\Colour_m40.bin bin\Colour_39.bin bin\Colour_m39.bin bin\Colour_41.bin bin\Colour_m41.bin

rem DataScorePanel.prg Must be at $8000 at the moment
SET OTHER_FILES=DataScorePanel.prg+2+! Sound\Citadel2_Title.prg+2 Citadel2_Title.dec+~$77 Citadel2_Game.dec+~$f7 Citadel2_Game2.dec+~$f7 Citadel2_Game3.dec+~$f7 DataLevel1.prg+2 ZonesLevel1.bin
SET /A NUM_FILES = SCROLLER_SPEED_CODE_FILES_NUM + 8
echo NUM_FILES=%NUM_FILES%

rem Get the final cart data offsets and link them in to the base code
..\bin\MakeCart.exe -tg -n -a $8000 -b 7 -f $2000 %NUM_FILES% %OTHER_FILES% %SCROLLER_SPEED_CODE_FILES%
..\acme.exe -f cbm -v3 --msvc --lib ../Scroller/ --lib ../Decompression/ Citadel2Entry.a Citadel2Entry_Game.a asm/Data.a >tf.txt
..\bin\LZMPi.exe -c64mr Citadel2.prg Citadel2.prg $200 >>tf.txt

..\bin\MakeCart.exe %CART_BOOT_TYPE% -n -a $8000 -b 0 -r ..\Citadel2\Citadel2Cart_8K.prg -c 0 2 $ffff -w %CART_BOOT_TYPE_HI% -r Citadel2.prg -a $8000 -b 1 -c 0 $0001 $ffff -w -a $8000 -b 2 -c 0 $2001 $ffff -w -a $8000 -b 3 -c 0 $4001 $ffff -w -a $8000 -b 4 -c 0 $6001 $ffff -w -a $8000 -b 5 -c 0 $8001 $ffff -w -a $8000 -b 6 -c 0 $a001 $ffff -w -a $8000 -b 7 -f $2000 %NUM_FILES% %OTHER_FILES% %SCROLLER_SPEED_CODE_FILES% -o Citadel2.crt >>tf.txt

C:\Downloads\WinVICE-3.1-x86-r34062\WinVICE-3.1-x86-r34062\cartconv.exe -i Citadel2.crt -t bin -o Citadel2.bin

goto end

:errorSpeed
echo Scroller_EnableSpeedCode is not enabled, it should always be
:error
echo Citadel2.prg not created!
exit /B -1
:end
