@echo off
del Citadel2.prg DataLevel1.prg Citadel2.crt Citadel2Cart.prg

..\acme.exe -v3 --msvc Citadel2Cart.a
if not exist Citadel2Cart.prg goto error

..\acme.exe -v3 --msvc --lib ../Scroller/ asm\DataScorePanel.a
if not exist DataScorePanel.prg goto error

..\acme.exe -v3 --msvc asm\DataLevel1.a
if not exist DataLevel1.prg goto error
..\bin\LZMPi.exe -c DataLevel1.prg DataLevel1.cmp $2 >t.txt

echo ;This file is automatically generated by BuildIt.bat >DataAutoDefs.a

rem Extract all the required variables from this list to a separate file
for %%x in (
	AnimationTypeTableHi
	AnimationTypeTableLo
	BackgroundFixedColours
	BlockColours
	BlockData
	CharColours
	EnemyAlertness
	EnemyBlockedCount
	EnemyHealth
	EnemyMoveGotMovement
	EnemyMoveStepsCount
	EnemyMoveStepsHi
	EnemyMoveStepsLo
	EnemyMoveStepsOriginalHi
	EnemyMoveStepsOriginalLo
	EnemyOffScreenCount
	EnemyPositionsX
	EnemyPositionsXHi
	EnemyPositionsXLo
	EnemyPositionsY
	EnemyPositionsYHi
	EnemyPositionsYLo
	EnemyPreviousSolveRequestX
	EnemyPreviousSolveRequestY
	EnemyRequestedRoute
	EnemySpeed
	EnemyToAnimationIndex
	EnemyType
	InterestingPlacesX
	InterestingPlacesY
	InterestingPlacesZone
	MapAnimationTypeTableLo
	MapAnimationTypeTableHi
	MapData
	MapTerminalToDoor
	NumInterestingPlaces
	TeleportPairs
) do (
	..\ExternalTools\Gnu\bin\sed.exe -n "/%%x/p" DataLevel1.map >>DataAutoDefs.a
)

for %%x in (
	ScorePanelChars
	ScorePanelColourLookup
	ScorePanelCharData
	TitleScreenChars
	TitleScreenCharData
	TitleScreenBallSprites
) do (
	..\ExternalTools\Gnu\bin\sed.exe -n "/%%x/p" DataScorePanel.map >>DataAutoDefs.a
)

..\acme.exe -v3 --msvc --lib ../Scroller/ --lib ../Decompression/ Citadel2Entry.a
if not exist Citadel2.prg goto error
copy /y Citadel2.prg Citadel2Orig.prg
..\bin\LZMPi.exe -c64b Citadel2.prg Citadel2.prg 1024 >>t.txt
if not exist Citadel2.prg goto error

..\bin\MakeCart.exe -n -b 0 -r Citadel2Cart.prg -c 0 2 $ffff -w -r Citadel2.prg -b 1 -c 0 $0001 $ffff -w -b 2 -c 0 $2001 $ffff -w -b 3 -c 0 $4001 $ffff -w -b 4 -c 0 $6001 $ffff -w -b 5 -c 0 $8001 $ffff -w -b 6 -c 0 $a001 $ffff -w -b 7 -r DataScorePanel.prg -c 0 2 $ffff -w -b 8 -r DataLevel1.cmp -c 0 2 $ffff -w -o Citadel2Cart.crt  >>t.txt

goto end

:error
echo Citadel2.prg not created!
exit -1
:end

