"%cd%\..\..\MusicStudio2\MusicStudio\Release\MusicStudio.exe" /hide /openFile "%cd%\Citadel_2_Music.msmus" /saveEnvelope 0B "%cd%\SFX Player Shoot.msenv" /saveEnvelope 0C "%cd%\SFX Player Destroyed.msenv" /saveEnvelope 0D "%cd%\SFX Alien Destroyed.msenv" /saveEnvelope 0E "%cd%\SFX Enter Terminal.msenv" /saveEnvelope 0F "%cd%\SFX TERMINAL COMPLETE.msenv" /saveEnvelope 10 "%cd%\SFX Termal Fail.msenv" /saveEnvelope 11 "%cd%\SFX SELECT.msenv" /saveEnvelope 12 "%cd%\SFX Exit Room.msenv" /exit


"%cd%\..\..\MusicStudio2\MusicStudio\Release\MusicStudio.exe" /hide /openFile "%cd%\Citadel_2_Music.msmus" /pressEnvelopeForceUsedFX 0B /pressEnvelopeForceUsedFX 0C /pressEnvelopeForceUsedFX 0F /pressEnvelopeForceUsedFX 14 /pressEnvelopeForceUsedFX 05 /deleteTrackPos 00 00 19 /deleteTrackPos 01 00 19 /deleteTrackPos 02 00 19 /deleteTrackPos 00 1A 19 /deleteTrackPos 01 1A 19 /deleteTrackPos 02 1A 19 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /insertEnvelope 00 /loadEnvelope 00 "%cd%\Explosion 1.msenv" /loadEnvelope 01 "%cd%\Explosion 2.msenv" /loadEnvelope 02 "%cd%\Explosion 3.msenv" /loadEnvelope 03 "%cd%\SFX Player Shoot.msenv" /loadEnvelope 04 "%cd%\SFX Player Destroyed.msenv" /loadEnvelope 05 "%cd%\SFX Alien Destroyed.msenv" /loadEnvelope 06 "%cd%\SFX Enter Terminal.msenv" /loadEnvelope 07 "%cd%\SFX TERMINAL COMPLETE.msenv" /loadEnvelope 08 "%cd%\SFX Termal Fail.msenv" /loadEnvelope 09 "%cd%\SFX SELECT.msenv" /loadEnvelope 0A "%cd%\SFX Exit Room.msenv" /pressEnvelopeForceUsedFX 00 /pressEnvelopeForceUsedFX 01 /pressEnvelopeForceUsedFX 02 /pressEnvelopeForceUsedFX 03 /pressEnvelopeForceUsedFX 04 /pressEnvelopeForceUsedFX 05 /pressEnvelopeForceUsedFX 06 /pressEnvelopeForceUsedFX 07 /pressEnvelopeForceUsedFX 08 /pressEnvelopeForceUsedFX 09 /pressEnvelopeForceUsedFX 0a /exportToC64 $8700 y "%cd%\Citadel2_Level1_SFX.prg" /exit


"%cd%\..\..\MusicStudio2\MusicStudio\Release\MusicStudio.exe" /hide /openFile "%cd%\Citadel_2_Music.msmus" /deleteTrackPos 00 19 20 /deleteTrackPos 01 19 20 /deleteTrackPos 02 19 20 /exportToC64 $8700 y "%cd%\Citadel2_Title.prg" /exit

"%cd%\..\..\ExternalTools\Gnu\bin\sed.exe" -n -e "s/volu. =//p" "%cd%\..\..\MusicStudio2\MusicStudio\t.map" > _tmpFile
set /p TEMPVAR= < _tmpFile
echo TitleMusic_Volume=%TEMPVAR% >Citadel2_Title_Offsets.a
