C:\work\c64\bin\Tok64.exe /stomp /totxt BLOCKEDIT.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt CLOCLEDIT.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt DEMO.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt DEMO2.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt MAKEUP.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt RACE.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt t.bat
C:\work\c64\bin\Tok64.exe /stomp /totxt TRACKOFT.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt TRACKPLOT.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt TRACKPOS.BA.PRG
C:\work\c64\bin\Tok64.exe /stomp /totxt TRACKPOSH.BA.PRG
