@echo off
del BlankProjectComp.prg

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

..\acme.exe -v3 --msvc BlankProjectComp.a
if not exist BlankProjectComp.prg goto error
rem ..\bin\LZMPi.exe -c64 BlankProjectComp.prg BlankProjectComp.prg $400 >t.txt
..\bin\LZMPi.exe -c64mr BlankProjectComp.prg BlankProjectComp.prg $400 >t.txt
if not exist BlankProjectComp.prg goto error
goto end
:error
echo BlankProjectComp.prg not created!
exit /B -1
:end
