..\MashSamples\Release\MashSamples a.wav 6000 ..\a.smp
..\MashSamples\Release\MashSamples Alert.wav 6000 ..\Alert.smp
..\MashSamples\Release\MashSamples Attack.wav 6000 ..\Attack.smp
..\MashSamples\Release\MashSamples Charge.wav 6000 ..\Charge.smp
..\MashSamples\Release\MashSamples Chicken.wav 6000 ..\Chicken.smp
..\MashSamples\Release\MashSamples Coins.wav 6000 ..\Coins.smp
..\MashSamples\Release\MashSamples Destroy.wav 6000 ..\Destroy.smp
..\MashSamples\Release\MashSamples Detected.wav 6000 ..\Detected.smp
..\MashSamples\Release\MashSamples Escape.wav 6000 ..\Escape.smp
..\MashSamples\Release\MashSamples Fight.wav 6000 ..\Fight.smp
..\MashSamples\Release\MashSamples Got.wav 6000 ..\Got.smp
..\MashSamples\Release\MashSamples Humanoid.wav 6000 ..\Humanoid.smp
..\MashSamples\Release\MashSamples In.wav 6000 ..\In.smp
..\MashSamples\Release\MashSamples Intruder.wav 6000 ..\Intruder.smp
..\MashSamples\Release\MashSamples Kill.wav 6000 ..\Kill.smp
..\MashSamples\Release\MashSamples Like.wav 6000 ..\Like.smp
..\MashSamples\Release\MashSamples Not.wav 6000 ..\Not.smp
..\MashSamples\Release\MashSamples Pocket.wav 6000 ..\Pocket.smp
..\MashSamples\Release\MashSamples Robot.wav 6000 ..\Robot.smp
..\MashSamples\Release\MashSamples The.wav 6000 ..\The.smp
..\MashSamples\Release\MashSamples Yes.wav 6000 ..\Yes.smp
..\MashSamples\Release\MashSamples It.wav 6000 ..\It.smp
..\MashSamples\Release\MashSamples Must.wav 6000 ..\Must.smp
..\MashSamples\Release\MashSamples BzztGTHGTI.wav 6000 ..\BzztGTHGTI.smp
..\MashSamples\Release\MashSamples Bzzt.wav 6000 ..\Bzzt.smp
..\MashSamples\Release\MashSamples FirePlayer.wav 6000 ..\FirePlayer.smp
..\MashSamples\Release\MashSamples FireRobot.wav 6000 ..\FireRobot.smp
