ren hunter-multicolour-doublewidth0.bmp                     hunter-multicolour-doublewidth000.bmp
ren hunter-multicolour-doublewidth1.bmp                     hunter-multicolour-doublewidth001.bmp
ren hunter-multicolour-doublewidth10.bmp                    hunter-multicolour-doublewidth010.bmp
ren hunter-multicolour-doublewidth100.bmp                   hunter-multicolour-doublewidth100.bmp
ren hunter-multicolour-doublewidth101.bmp                   hunter-multicolour-doublewidth101.bmp
ren hunter-multicolour-doublewidth102.bmp                   hunter-multicolour-doublewidth102.bmp
ren hunter-multicolour-doublewidth103.bmp                   hunter-multicolour-doublewidth103.bmp
ren hunter-multicolour-doublewidth104.bmp                   hunter-multicolour-doublewidth104.bmp
ren hunter-multicolour-doublewidth105.bmp                   hunter-multicolour-doublewidth105.bmp
ren hunter-multicolour-doublewidth106.bmp                   hunter-multicolour-doublewidth106.bmp
ren hunter-multicolour-doublewidth107.bmp                   hunter-multicolour-doublewidth107.bmp
ren hunter-multicolour-doublewidth108.bmp                   hunter-multicolour-doublewidth108.bmp
ren hunter-multicolour-doublewidth109.bmp                   hunter-multicolour-doublewidth109.bmp
ren hunter-multicolour-doublewidth11.bmp                    hunter-multicolour-doublewidth011.bmp
ren hunter-multicolour-doublewidth110.bmp                   hunter-multicolour-doublewidth110.bmp
ren hunter-multicolour-doublewidth111.bmp                   hunter-multicolour-doublewidth111.bmp
ren hunter-multicolour-doublewidth112.bmp                   hunter-multicolour-doublewidth112.bmp
ren hunter-multicolour-doublewidth113.bmp                   hunter-multicolour-doublewidth113.bmp
ren hunter-multicolour-doublewidth114.bmp                   hunter-multicolour-doublewidth114.bmp
ren hunter-multicolour-doublewidth115.bmp                   hunter-multicolour-doublewidth115.bmp
ren hunter-multicolour-doublewidth116.bmp                   hunter-multicolour-doublewidth116.bmp
ren hunter-multicolour-doublewidth117.bmp                   hunter-multicolour-doublewidth117.bmp
ren hunter-multicolour-doublewidth118.bmp                   hunter-multicolour-doublewidth118.bmp
ren hunter-multicolour-doublewidth119.bmp                   hunter-multicolour-doublewidth119.bmp
ren hunter-multicolour-doublewidth12.bmp                    hunter-multicolour-doublewidth012.bmp
ren hunter-multicolour-doublewidth120.bmp                   hunter-multicolour-doublewidth120.bmp
ren hunter-multicolour-doublewidth121.bmp                   hunter-multicolour-doublewidth121.bmp
ren hunter-multicolour-doublewidth122.bmp                   hunter-multicolour-doublewidth122.bmp
ren hunter-multicolour-doublewidth123.bmp                   hunter-multicolour-doublewidth123.bmp
ren hunter-multicolour-doublewidth124.bmp                   hunter-multicolour-doublewidth124.bmp
ren hunter-multicolour-doublewidth125.bmp                   hunter-multicolour-doublewidth125.bmp
ren hunter-multicolour-doublewidth126.bmp                   hunter-multicolour-doublewidth126.bmp
ren hunter-multicolour-doublewidth127.bmp                   hunter-multicolour-doublewidth127.bmp
ren hunter-multicolour-doublewidth128.bmp                   hunter-multicolour-doublewidth128.bmp
ren hunter-multicolour-doublewidth129.bmp                   hunter-multicolour-doublewidth129.bmp
ren hunter-multicolour-doublewidth13.bmp                    hunter-multicolour-doublewidth013.bmp
ren hunter-multicolour-doublewidth130.bmp                   hunter-multicolour-doublewidth130.bmp
ren hunter-multicolour-doublewidth131.bmp                   hunter-multicolour-doublewidth131.bmp
ren hunter-multicolour-doublewidth132.bmp                   hunter-multicolour-doublewidth132.bmp
ren hunter-multicolour-doublewidth133.bmp                   hunter-multicolour-doublewidth133.bmp
ren hunter-multicolour-doublewidth134.bmp                   hunter-multicolour-doublewidth134.bmp
ren hunter-multicolour-doublewidth135.bmp                   hunter-multicolour-doublewidth135.bmp
ren hunter-multicolour-doublewidth136.bmp                   hunter-multicolour-doublewidth136.bmp
ren hunter-multicolour-doublewidth137.bmp                   hunter-multicolour-doublewidth137.bmp
ren hunter-multicolour-doublewidth138.bmp                   hunter-multicolour-doublewidth138.bmp
ren hunter-multicolour-doublewidth139.bmp                   hunter-multicolour-doublewidth139.bmp
ren hunter-multicolour-doublewidth14.bmp                    hunter-multicolour-doublewidth014.bmp
ren hunter-multicolour-doublewidth140.bmp                   hunter-multicolour-doublewidth140.bmp
ren hunter-multicolour-doublewidth141.bmp                   hunter-multicolour-doublewidth141.bmp
ren hunter-multicolour-doublewidth142.bmp                   hunter-multicolour-doublewidth142.bmp
ren hunter-multicolour-doublewidth143.bmp                   hunter-multicolour-doublewidth143.bmp
ren hunter-multicolour-doublewidth144.bmp                   hunter-multicolour-doublewidth144.bmp
ren hunter-multicolour-doublewidth145.bmp                   hunter-multicolour-doublewidth145.bmp
ren hunter-multicolour-doublewidth146.bmp                   hunter-multicolour-doublewidth146.bmp
ren hunter-multicolour-doublewidth147.bmp                   hunter-multicolour-doublewidth147.bmp
ren hunter-multicolour-doublewidth148.bmp                   hunter-multicolour-doublewidth148.bmp
ren hunter-multicolour-doublewidth149.bmp                   hunter-multicolour-doublewidth149.bmp
ren hunter-multicolour-doublewidth15.bmp                    hunter-multicolour-doublewidth015.bmp
ren hunter-multicolour-doublewidth16.bmp                    hunter-multicolour-doublewidth016.bmp
ren hunter-multicolour-doublewidth17.bmp                    hunter-multicolour-doublewidth017.bmp
ren hunter-multicolour-doublewidth18.bmp                    hunter-multicolour-doublewidth018.bmp
ren hunter-multicolour-doublewidth19.bmp                    hunter-multicolour-doublewidth019.bmp
ren hunter-multicolour-doublewidth2.bmp                     hunter-multicolour-doublewidth002.bmp
ren hunter-multicolour-doublewidth20.bmp                    hunter-multicolour-doublewidth020.bmp
ren hunter-multicolour-doublewidth21.bmp                    hunter-multicolour-doublewidth021.bmp
ren hunter-multicolour-doublewidth22.bmp                    hunter-multicolour-doublewidth022.bmp
ren hunter-multicolour-doublewidth23.bmp                    hunter-multicolour-doublewidth023.bmp
ren hunter-multicolour-doublewidth24.bmp                    hunter-multicolour-doublewidth024.bmp
ren hunter-multicolour-doublewidth25.bmp                    hunter-multicolour-doublewidth025.bmp
ren hunter-multicolour-doublewidth26.bmp                    hunter-multicolour-doublewidth026.bmp
ren hunter-multicolour-doublewidth27.bmp                    hunter-multicolour-doublewidth027.bmp
ren hunter-multicolour-doublewidth28.bmp                    hunter-multicolour-doublewidth028.bmp
ren hunter-multicolour-doublewidth29.bmp                    hunter-multicolour-doublewidth029.bmp
ren hunter-multicolour-doublewidth3.bmp                     hunter-multicolour-doublewidth003.bmp
ren hunter-multicolour-doublewidth30.bmp                    hunter-multicolour-doublewidth030.bmp
ren hunter-multicolour-doublewidth31.bmp                    hunter-multicolour-doublewidth031.bmp
ren hunter-multicolour-doublewidth32.bmp                    hunter-multicolour-doublewidth032.bmp
ren hunter-multicolour-doublewidth33.bmp                    hunter-multicolour-doublewidth033.bmp
ren hunter-multicolour-doublewidth34.bmp                    hunter-multicolour-doublewidth034.bmp
ren hunter-multicolour-doublewidth35.bmp                    hunter-multicolour-doublewidth035.bmp
ren hunter-multicolour-doublewidth36.bmp                    hunter-multicolour-doublewidth036.bmp
ren hunter-multicolour-doublewidth37.bmp                    hunter-multicolour-doublewidth037.bmp
ren hunter-multicolour-doublewidth38.bmp                    hunter-multicolour-doublewidth038.bmp
ren hunter-multicolour-doublewidth39.bmp                    hunter-multicolour-doublewidth039.bmp
ren hunter-multicolour-doublewidth4.bmp                     hunter-multicolour-doublewidth004.bmp
ren hunter-multicolour-doublewidth40.bmp                    hunter-multicolour-doublewidth040.bmp
ren hunter-multicolour-doublewidth41.bmp                    hunter-multicolour-doublewidth041.bmp
ren hunter-multicolour-doublewidth42.bmp                    hunter-multicolour-doublewidth042.bmp
ren hunter-multicolour-doublewidth43.bmp                    hunter-multicolour-doublewidth043.bmp
ren hunter-multicolour-doublewidth44.bmp                    hunter-multicolour-doublewidth044.bmp
ren hunter-multicolour-doublewidth45.bmp                    hunter-multicolour-doublewidth045.bmp
ren hunter-multicolour-doublewidth46.bmp                    hunter-multicolour-doublewidth046.bmp
ren hunter-multicolour-doublewidth47.bmp                    hunter-multicolour-doublewidth047.bmp
ren hunter-multicolour-doublewidth48.bmp                    hunter-multicolour-doublewidth048.bmp
ren hunter-multicolour-doublewidth49.bmp                    hunter-multicolour-doublewidth049.bmp
ren hunter-multicolour-doublewidth5.bmp                     hunter-multicolour-doublewidth005.bmp
ren hunter-multicolour-doublewidth50.bmp                    hunter-multicolour-doublewidth050.bmp
ren hunter-multicolour-doublewidth51.bmp                    hunter-multicolour-doublewidth051.bmp
ren hunter-multicolour-doublewidth52.bmp                    hunter-multicolour-doublewidth052.bmp
ren hunter-multicolour-doublewidth53.bmp                    hunter-multicolour-doublewidth053.bmp
ren hunter-multicolour-doublewidth54.bmp                    hunter-multicolour-doublewidth054.bmp
ren hunter-multicolour-doublewidth55.bmp                    hunter-multicolour-doublewidth055.bmp
ren hunter-multicolour-doublewidth56.bmp                    hunter-multicolour-doublewidth056.bmp
ren hunter-multicolour-doublewidth57.bmp                    hunter-multicolour-doublewidth057.bmp
ren hunter-multicolour-doublewidth58.bmp                    hunter-multicolour-doublewidth058.bmp
ren hunter-multicolour-doublewidth59.bmp                    hunter-multicolour-doublewidth059.bmp
ren hunter-multicolour-doublewidth6.bmp                     hunter-multicolour-doublewidth006.bmp
ren hunter-multicolour-doublewidth60.bmp                    hunter-multicolour-doublewidth060.bmp
ren hunter-multicolour-doublewidth61.bmp                    hunter-multicolour-doublewidth061.bmp
ren hunter-multicolour-doublewidth62.bmp                    hunter-multicolour-doublewidth062.bmp
ren hunter-multicolour-doublewidth63.bmp                    hunter-multicolour-doublewidth063.bmp
ren hunter-multicolour-doublewidth64.bmp                    hunter-multicolour-doublewidth064.bmp
ren hunter-multicolour-doublewidth65.bmp                    hunter-multicolour-doublewidth065.bmp
ren hunter-multicolour-doublewidth66.bmp                    hunter-multicolour-doublewidth066.bmp
ren hunter-multicolour-doublewidth67.bmp                    hunter-multicolour-doublewidth067.bmp
ren hunter-multicolour-doublewidth68.bmp                    hunter-multicolour-doublewidth068.bmp
ren hunter-multicolour-doublewidth69.bmp                    hunter-multicolour-doublewidth069.bmp
ren hunter-multicolour-doublewidth7.bmp                     hunter-multicolour-doublewidth007.bmp
ren hunter-multicolour-doublewidth70.bmp                    hunter-multicolour-doublewidth070.bmp
ren hunter-multicolour-doublewidth71.bmp                    hunter-multicolour-doublewidth071.bmp
ren hunter-multicolour-doublewidth72.bmp                    hunter-multicolour-doublewidth072.bmp
ren hunter-multicolour-doublewidth73.bmp                    hunter-multicolour-doublewidth073.bmp
ren hunter-multicolour-doublewidth74.bmp                    hunter-multicolour-doublewidth074.bmp
ren hunter-multicolour-doublewidth75.bmp                    hunter-multicolour-doublewidth075.bmp
ren hunter-multicolour-doublewidth76.bmp                    hunter-multicolour-doublewidth076.bmp
ren hunter-multicolour-doublewidth77.bmp                    hunter-multicolour-doublewidth077.bmp
ren hunter-multicolour-doublewidth78.bmp                    hunter-multicolour-doublewidth078.bmp
ren hunter-multicolour-doublewidth79.bmp                    hunter-multicolour-doublewidth079.bmp
ren hunter-multicolour-doublewidth8.bmp                     hunter-multicolour-doublewidth008.bmp
ren hunter-multicolour-doublewidth80.bmp                    hunter-multicolour-doublewidth080.bmp
ren hunter-multicolour-doublewidth81.bmp                    hunter-multicolour-doublewidth081.bmp
ren hunter-multicolour-doublewidth82.bmp                    hunter-multicolour-doublewidth082.bmp
ren hunter-multicolour-doublewidth83.bmp                    hunter-multicolour-doublewidth083.bmp
ren hunter-multicolour-doublewidth84.bmp                    hunter-multicolour-doublewidth084.bmp
ren hunter-multicolour-doublewidth85.bmp                    hunter-multicolour-doublewidth085.bmp
ren hunter-multicolour-doublewidth86.bmp                    hunter-multicolour-doublewidth086.bmp
ren hunter-multicolour-doublewidth87.bmp                    hunter-multicolour-doublewidth087.bmp
ren hunter-multicolour-doublewidth88.bmp                    hunter-multicolour-doublewidth088.bmp
ren hunter-multicolour-doublewidth89.bmp                    hunter-multicolour-doublewidth089.bmp
ren hunter-multicolour-doublewidth9.bmp                     hunter-multicolour-doublewidth009.bmp
ren hunter-multicolour-doublewidth90.bmp                    hunter-multicolour-doublewidth090.bmp
ren hunter-multicolour-doublewidth91.bmp                    hunter-multicolour-doublewidth091.bmp
ren hunter-multicolour-doublewidth92.bmp                    hunter-multicolour-doublewidth092.bmp
ren hunter-multicolour-doublewidth93.bmp                    hunter-multicolour-doublewidth093.bmp
ren hunter-multicolour-doublewidth94.bmp                    hunter-multicolour-doublewidth094.bmp
ren hunter-multicolour-doublewidth95.bmp                    hunter-multicolour-doublewidth095.bmp
ren hunter-multicolour-doublewidth96.bmp                    hunter-multicolour-doublewidth096.bmp
ren hunter-multicolour-doublewidth97.bmp                    hunter-multicolour-doublewidth097.bmp
ren hunter-multicolour-doublewidth98.bmp                    hunter-multicolour-doublewidth098.bmp
ren hunter-multicolour-doublewidth99.bmp                    hunter-multicolour-doublewidth099.bmp


rem C:\Downloads\ImageMagick-7.0.7-4-portable-Q16-x64\convert.exe -verbose hunter-multicolour-doublewidth*.bmp -extent 320x200 -type truecolor frm%%05d.bmp
C:\Downloads\ImageMagick-7.0.7-4-portable-Q16-x64\convert.exe -verbose hunter-multicolour-doublewidth*.bmp -background black -extent 320x200 -type truecolor frm%%05d.bmp
