@echo off
del Craptastic2.prg

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

..\acme.exe --lib ..\ -v9 --msvc main.a
if not exist Craptastic2.prg goto error
..\bin\LZMPi.exe -c64mu Craptastic2.prg Craptastic2.prg $900
if not exist Craptastic2.prg goto error
goto end
:error
echo Craptastic2.prg not created!
exit /B -1
:end
