@echo off
del Craptastic3.prg

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

..\acme.exe --lib ..\ --lib ..\SpriteMultiplexor\ -v9 --msvc main.a
if not exist Craptastic3.prg goto error
rem 3654
..\bin\LZMPi.exe -ol 200 -c64v Craptastic3.prg Craptastic3max.prg $900
rem 3728
..\bin\LZMPi.exe -c64mu Craptastic3.prg Craptastic3.prg $900
if not exist Craptastic3.prg goto error
goto end
:error
echo Craptastic3.prg not created!
exit /B -1
:end
