@echo off
pushd %~dp0
del bin\main6a.prg bin\main6b.prg bin\main6c.prg bin\main.crt
if not exist tmp mkdir tmp
if not exist bin mkdir bin

echo ;This file is automatically generated by BuildIt.bat >tmp\FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>tmp\FingerPrint.a

del bin\main.prg
..\acme.exe -v4 --lib ../ --lib ../../ --lib ../../../ --msvc asm/main6.a
if not exist bin\main.prg goto error
copy /y bin\main.prg bin\main6a.prg
copy /y tmp\main.pdb tmp\main6a.pdb

del bin\main.prg
..\acme.exe -v4 --lib ../ --lib ../../ --lib ../../../ --msvc asm/main6b.a
if not exist bin\main.prg goto error
copy /y bin\main.prg bin\main6b.prg
copy /y tmp\main.pdb tmp\main6b.pdb


set DEMO_SPEED_CODE_FILES_NUM=34
set DEMO_SPEED_CODE_FILES=bin\main6a.prg+2 bin\main6b.prg+2 tmp\ShadowBeastPaletteData.bin tmp\ShadowBeastSprites2_plane0.bin tmp\ShadowBeastSprites2_plane1.bin tmp\ShadowBeastSprites2_plane2.bin tmp\ShadowBeastSprites2_plane3.bin tmp\ShadowBeastChars2_map.bin tmp\ShadowBeastChars2_map.bin2 tmp\ShadowBeastChars2_plane0.bin tmp\ShadowBeastChars2_plane1.bin tmp\ShadowBeastChars2_plane2.bin tmp\ShadowBeastChars2_plane3.bin tmp\ShadowBeastTiles_map.bin tmp\ShadowBeastTiles_plane0.bin tmp\ShadowBeastTiles_plane1.bin tmp\ShadowBeastTiles_plane2.bin tmp\ShadowBeastTiles_plane3.bin tmp\ShadowBeastSprites_plane0.bin tmp\ShadowBeastSprites_plane1.bin tmp\ShadowBeastSprites_plane2.bin tmp\ShadowBeastSprites_plane3.bin tmp\ShadowBeastChars_map.bin tmp\ShadowBeastChars_map.bin2 tmp\ShadowBeastChars_plane0.bin tmp\ShadowBeastChars_plane1.bin tmp\ShadowBeastChars_plane2.bin tmp\ShadowBeastChars_plane3.bin tmp\Demo6Sprites20.bin tmp\Demo6Sprites21.bin tmp\Demo6Sprites22.bin tmp\Demo6Sprites23.bin tmp\target\SotBexportedMusicSamples.bin tmp\target\SotBexportedMusic2Samples.bin

echo Calculating index file
..\bin\MakeCart.exe -i tmp\_f_index1.a -te -n -a $8000 -s $2000 -b 1 -f $2000 %DEMO_SPEED_CODE_FILES_NUM% %DEMO_SPEED_CODE_FILES% -s 0 -o bin\main.crt


del bin\main.prg
..\acme.exe -v4 --lib ../ --lib ../../ --lib ../../../ --msvc asm/main6c.a
if not exist bin\main.prg goto error
copy /y bin\main.prg bin\main6c.prg
copy /y tmp\main.pdb tmp\main6c.pdb


..\bin\MakeCart.exe -i tmp\_f_index1.a -te -n -a $8000 -b 0 -r bin\main6c.prg -c 0 2 $ffff -w -a $a000 -b 0 -c $1ffc 2 4 -w -a $8000 -s $2000 -b 1 -f $2000 %DEMO_SPEED_CODE_FILES_NUM% %DEMO_SPEED_CODE_FILES% -s 0 -o bin\main.crt



rem --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED
rem -Xmx256M -Xms256M
rem -DZbdd6502.trace=true
rem "C:\Users\Martin Piper\.jdks\corretto-1.8.0_252\bin\java.exe"
java.exe -Xincgc -Xmx256M -Xms256M -jar ..\..\BDD6502\target\BDD6502-1.0.9-SNAPSHOT-jar-with-dependencies.jar --tags @Demo6C --monochrome --plugin pretty --plugin html:target/cucumber --plugin json:target/report1.json --glue macros --glue TestGlue features

goto end
:error
echo main.cmp.prg not created!
exit /B -1
:end
popd
