@echo off
pushd %~dp0
del bin\main.prg
del bin\main.cmp.prg
if not exist tmp mkdir tmp
if not exist bin mkdir bin

echo ;This file is automatically generated by BuildIt.bat >tmp\FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>tmp\FingerPrint.a

echo Calculating index file
..\bin\MakeCart.exe -i tmp\_f_index1.a -te -n -a $8000 -s $2000 -b 0 -w -b 1 -m assets\Demo9\RenderFloor\hor\*.hor $2000 -s 0 -o bin\main.crt

..\acme.exe -v4 --lib ../ --lib ../../ --lib ../../../ --msvc asm/main9.a
if not exist bin\main.prg goto error
rem Reduce zeropage corruption
rem ..\bin\LZMPi.exe -c64 bin\main.prg bin\main.cmp.prg $200 >tmp\t.txt
..\bin\LZMPi.exe -c64mr bin\main.prg bin\main.cmp.prg $200 >tmp\t.txt
if not exist bin\main.cmp.prg goto error

rem --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED
rem -Xmx256M -Xms256M
rem -DZbdd6502.trace=true
rem "C:\Users\Martin Piper\.jdks\corretto-1.8.0_252\bin\java.exe"
java.exe -Xincgc -Xmx512M -Xms512M -jar ..\..\BDD6502\target\BDD6502-1.0.9-SNAPSHOT-jar-with-dependencies.jar --tags @Demo9 --monochrome --plugin pretty --plugin html:target/cucumber --plugin json:target/report1.json --glue macros --glue TestGlue features

goto end
:error
echo main.cmp.prg not created!
exit /B -1
:end
popd
