@echo off
pushd %~dp0
del bin\main.prg
del bin\main.cmp.prg
if not exist tmp mkdir tmp
if not exist bin mkdir bin

echo ;This file is automatically generated by BuildIt.bat >tmp\FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>tmp\FingerPrint.a

..\acme.exe -v4 --lib ../ --lib ../../ --lib ../../../ --msvc asm/main3MultiplexAPU.a
if not exist bin\main.prg goto error
rem ..\bin\LZMPi.exe -c64 bin\main.prg bin\main.cmp.prg $200 >tmp\t.txt
..\bin\LZMPi.exe -c64mr bin\main.prg bin\main.cmp.prg $200 >tmp\t.txt
if not exist bin\main.cmp.prg goto error


rem Extract APU code and data to separate chunks for hardware simulation to use
..\ExternalTools\Gnu\bin\sed.exe -n -e "s/APUCode_Start. =\$//p" tmp\main.map > tmp\_tmpFile
set /p CODE_APUCODE_START= < tmp\_tmpFile
set /A FILE_APUCODE_START=0x%CODE_APUCODE_START% + 2 - 0x200

..\ExternalTools\Gnu\bin\sed.exe -n -e "s/APUCode_Size. =\$//p" tmp\main.map > tmp\_tmpFile
set /p FILE_APUCODE_SIZE= < tmp\_tmpFile
set /A FILE_APUCODE_SIZE=0x%FILE_APUCODE_SIZE%

..\bin\LZMPi.exe -cut bin\main.prg bin\apucode.bin %FILE_APUCODE_START% %FILE_APUCODE_SIZE%


..\ExternalTools\Gnu\bin\sed.exe -n -e "s/APUData_Start. =\$//p" tmp\main.map > tmp\_tmpFile
set /p CODE_APUDATA_START= < tmp\_tmpFile
set /A FILE_APUDATA_START=0x%CODE_APUDATA_START% + 2 - 0x200

..\ExternalTools\Gnu\bin\sed.exe -n -e "s/APUData_Size. =\$//p" tmp\main.map > tmp\_tmpFile
set /p FILE_APUDATA_SIZE= < tmp\_tmpFile
set /A FILE_APUDATA_SIZE=0x%FILE_APUDATA_SIZE%

..\bin\LZMPi.exe -cut bin\main.prg bin\apudata.bin %FILE_APUDATA_START% %FILE_APUDATA_SIZE%



rem --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED
rem -Xmx256M -Xms256M
rem -DZbdd6502.trace=true
rem "C:\Users\Martin Piper\.jdks\corretto-1.8.0_252\bin\java.exe"
java.exe -Xincgc -Xmx256M -Xms256M -jar ..\..\BDD6502\target\BDD6502-1.0.9-SNAPSHOT-jar-with-dependencies.jar --tags @Demo3 --monochrome --plugin pretty --plugin html:target/cucumber --plugin json:target/report1.json --glue macros --glue TestGlue features

goto end
:error
echo main.cmp.prg not created!
exit /B -1
:end
popd
