call assets\convert.bat
call assets\convert3.bat
call assets\convert4.bat
call assets\convert5.bat
call assets\convert6.bat
call assets\convert7.bat
call assets\convert9.bat
call assets\convert10.bat
call assets\convert11.bat
call assets\convert13.bat
call assets\convert14.bat

call BuildIt.bat
call BuildIt3.bat
call BuildIt3Anim.bat
call BuildIt3MultiplexAPU.bat
call BuildIt3MultiplexTimer.bat
call BuildIt4.bat
call BuildIt5.bat
call BuildIt6.bat
call BuildIt6b.bat
call BuildIt6c.bat
call BuildIt7.bat
call BuildIt9.bat
call BuildIt10.bat
call BuildIt11.bat
call BuildIt12.bat
call BuildIt13.bat
call BuildIt143.bat
