del *.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_0.bmp"             scene6_composite_000.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_1.bmp"             scene6_composite_001.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_10.bmp"            scene6_composite_010.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_100.bmp"           scene6_composite_100.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_101.bmp"           scene6_composite_101.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_102.bmp"           scene6_composite_102.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_103.bmp"           scene6_composite_103.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_104.bmp"           scene6_composite_104.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_105.bmp"           scene6_composite_105.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_106.bmp"           scene6_composite_106.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_107.bmp"           scene6_composite_107.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_108.bmp"           scene6_composite_108.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_109.bmp"           scene6_composite_109.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_11.bmp"            scene6_composite_011.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_110.bmp"           scene6_composite_110.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_111.bmp"           scene6_composite_111.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_112.bmp"           scene6_composite_112.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_113.bmp"           scene6_composite_113.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_114.bmp"           scene6_composite_114.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_115.bmp"           scene6_composite_115.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_116.bmp"           scene6_composite_116.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_117.bmp"           scene6_composite_117.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_118.bmp"           scene6_composite_118.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_119.bmp"           scene6_composite_119.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_12.bmp"            scene6_composite_012.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_120.bmp"           scene6_composite_120.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_121.bmp"           scene6_composite_121.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_122.bmp"           scene6_composite_122.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_123.bmp"           scene6_composite_123.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_124.bmp"           scene6_composite_124.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_125.bmp"           scene6_composite_125.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_126.bmp"           scene6_composite_126.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_127.bmp"           scene6_composite_127.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_128.bmp"           scene6_composite_128.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_129.bmp"           scene6_composite_129.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_13.bmp"            scene6_composite_013.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_130.bmp"           scene6_composite_130.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_131.bmp"           scene6_composite_131.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_132.bmp"           scene6_composite_132.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_133.bmp"           scene6_composite_133.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_134.bmp"           scene6_composite_134.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_135.bmp"           scene6_composite_135.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_136.bmp"           scene6_composite_136.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_137.bmp"           scene6_composite_137.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_138.bmp"           scene6_composite_138.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_139.bmp"           scene6_composite_139.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_14.bmp"            scene6_composite_014.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_140.bmp"           scene6_composite_140.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_141.bmp"           scene6_composite_141.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_142.bmp"           scene6_composite_142.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_143.bmp"           scene6_composite_143.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_144.bmp"           scene6_composite_144.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_145.bmp"           scene6_composite_145.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_146.bmp"           scene6_composite_146.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_147.bmp"           scene6_composite_147.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_148.bmp"           scene6_composite_148.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_149.bmp"           scene6_composite_149.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_15.bmp"            scene6_composite_015.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_16.bmp"            scene6_composite_016.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_17.bmp"            scene6_composite_017.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_18.bmp"            scene6_composite_018.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_19.bmp"            scene6_composite_019.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_2.bmp"             scene6_composite_002.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_20.bmp"            scene6_composite_020.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_21.bmp"            scene6_composite_021.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_22.bmp"            scene6_composite_022.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_23.bmp"            scene6_composite_023.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_24.bmp"            scene6_composite_024.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_25.bmp"            scene6_composite_025.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_26.bmp"            scene6_composite_026.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_27.bmp"            scene6_composite_027.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_28.bmp"            scene6_composite_028.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_29.bmp"            scene6_composite_029.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_3.bmp"             scene6_composite_003.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_30.bmp"            scene6_composite_030.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_31.bmp"            scene6_composite_031.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_32.bmp"            scene6_composite_032.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_33.bmp"            scene6_composite_033.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_34.bmp"            scene6_composite_034.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_35.bmp"            scene6_composite_035.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_36.bmp"            scene6_composite_036.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_37.bmp"            scene6_composite_037.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_38.bmp"            scene6_composite_038.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_39.bmp"            scene6_composite_039.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_4.bmp"             scene6_composite_004.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_40.bmp"            scene6_composite_040.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_41.bmp"            scene6_composite_041.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_42.bmp"            scene6_composite_042.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_43.bmp"            scene6_composite_043.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_44.bmp"            scene6_composite_044.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_45.bmp"            scene6_composite_045.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_46.bmp"            scene6_composite_046.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_47.bmp"            scene6_composite_047.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_48.bmp"            scene6_composite_048.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_49.bmp"            scene6_composite_049.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_5.bmp"             scene6_composite_005.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_50.bmp"            scene6_composite_050.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_51.bmp"            scene6_composite_051.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_52.bmp"            scene6_composite_052.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_53.bmp"            scene6_composite_053.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_54.bmp"            scene6_composite_054.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_55.bmp"            scene6_composite_055.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_56.bmp"            scene6_composite_056.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_57.bmp"            scene6_composite_057.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_58.bmp"            scene6_composite_058.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_59.bmp"            scene6_composite_059.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_6.bmp"             scene6_composite_006.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_60.bmp"            scene6_composite_060.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_61.bmp"            scene6_composite_061.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_62.bmp"            scene6_composite_062.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_63.bmp"            scene6_composite_063.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_64.bmp"            scene6_composite_064.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_65.bmp"            scene6_composite_065.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_66.bmp"            scene6_composite_066.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_67.bmp"            scene6_composite_067.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_68.bmp"            scene6_composite_068.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_69.bmp"            scene6_composite_069.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_7.bmp"             scene6_composite_007.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_70.bmp"            scene6_composite_070.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_71.bmp"            scene6_composite_071.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_72.bmp"            scene6_composite_072.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_73.bmp"            scene6_composite_073.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_74.bmp"            scene6_composite_074.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_75.bmp"            scene6_composite_075.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_76.bmp"            scene6_composite_076.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_77.bmp"            scene6_composite_077.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_78.bmp"            scene6_composite_078.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_79.bmp"            scene6_composite_079.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_8.bmp"             scene6_composite_008.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_80.bmp"            scene6_composite_080.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_81.bmp"            scene6_composite_081.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_82.bmp"            scene6_composite_082.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_83.bmp"            scene6_composite_083.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_84.bmp"            scene6_composite_084.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_85.bmp"            scene6_composite_085.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_86.bmp"            scene6_composite_086.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_87.bmp"            scene6_composite_087.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_88.bmp"            scene6_composite_088.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_89.bmp"            scene6_composite_089.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_9.bmp"             scene6_composite_009.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_90.bmp"            scene6_composite_090.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_91.bmp"            scene6_composite_091.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_92.bmp"            scene6_composite_092.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_93.bmp"            scene6_composite_093.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_94.bmp"            scene6_composite_094.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_95.bmp"            scene6_composite_095.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_96.bmp"            scene6_composite_096.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_97.bmp"            scene6_composite_097.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_98.bmp"            scene6_composite_098.bmp
copy "C:\Users\Martin Piper\Downloads\HMScene6\flattened_demo\flattened_demo\scene6_composite_99.bmp"            scene6_composite_099.bmp


C:\Downloads\ImageMagick-7.0.7-4-portable-Q16-x64\convert.exe -verbose scene6_composite_*.bmp -background black -gravity north -extent 320x200 -type truecolor frm%%05d.bmp
