@echo off
mkdir bin

set CART_BOOT_TYPE=-tg
set CART_BOOT_TYPE_HI=-a $8000

echo ;This file is automatically generated by BuildIt.bat >FingerPrint.a
echo !scr "%TIME% %DATE% %COMPUTERNAME% %USERNAME%" >>FingerPrint.a

FOR %%G IN (AggressorTheme AlteredBeast Armalyte AtomicRoboKid Chameleon Citadel Dominion DragonBreed FinalBlow GalaxyForceII IndianaJonesFateofAtlantis NinjaSpirit Rodland RupertandtheToymakersParty SecretProject Snare Speedball2 SWIV TimeMachine WalkersWarbles) DO (
	echo Processing %%G
	del MusicMultiSelect.prg
	..\acme.exe --lib ..\ -v4 --msvc Main.a inc\Music%%G.a Player.a
	if not exist MusicMultiSelect.prg goto error
	..\bin\LZMPi.exe -c64mr MusicMultiSelect.prg bin\MusicMultiSelect_%%G.prg $300 >bin\t.txt
rem	..\bin\LZMPi.exe -c64mu MusicMultiSelect.prg bin\MusicMultiSelect_%%G.prg $300 >bin\t.txt
)

rem Include wildcard files, these can span banks
..\bin\MakeCart.exe -i bin\_f_index1.a -tg -n -a $8000 -b 7 -s $2000 -m bin\id*.txt $2000 s:bin\Music*.prg -o MusicMultiSelect.crt >>bin\t.txt

rem Assemble the main select system using the output music index
del MultiSelectSystem.prg
..\acme.exe --lib ..\ -v4 --msvc MultiSelectSystem.a
if not exist MultiSelectSystem.prg goto error
..\bin\LZMPi.exe -c64mr MultiSelectSystem.prg MultiSelectSystem.prg $300 >bin\t.txt

rem Build the final cart
..\bin\MakeCart.exe %CART_BOOT_TYPE% -n -a $8000 -b 0 -r ..\Citadel2\Citadel2Cart_8K.prg -c 0 2 $ffff -w %CART_BOOT_TYPE_HI% -r MultiSelectSystem.prg -a $8000 -b 1 -c 0 $0001 $ffff -w -a $8000 -b 2 -c 0 $2001 $ffff -w -a $8000 -b 3 -c 0 $4001 $ffff -w -a $8000 -b 4 -c 0 $6001 $ffff -w -a $8000 -b 5 -c 0 $8001 $ffff -w -a $8000 -b 6 -c 0 $a001 $ffff -w -a $8000 -b 7 -s $2000 -m bin\id*.txt $2000 s:bin\Music*.prg -o MusicMultiSelect.crt >>bin\t.txt

goto end
:error
echo MusicMultiSelect.prg not created!
exit /B -1
:end

